runtime: php83

entrypoint: serve index.php

handlers:
  - url: /css
    static_dir: css
  - url: /fonts
    static_dir: fonts
  - url: /img
    static_dir: img
  - url: /js
    static_dir: js
  - url: /.*
    script: auto
    secure: always

env_variables:
  DB_SOCKET: '/cloudsql/e-03-452916:us-central1:gamebos' # Instance connection name Anda
  DB_NAME: 'gamebosdb' # Nama database Anda
  DB_USER: 'ester' # Username database Anda
  DB_PASS: '' # GANTI DENGAN PASSWORD KUAT YANG SUDAH ANDA BUAT
  GCS_BUCKET_NAME: 'ta-tcc' # Nama bucket Anda
