runtime: php81

handlers:
  - url: /css
    static_dir: css

  - url: /fonts
    static_dir: fonts

  - url: /img
    static_dir: img

  - url: /js
    static_dir: js

  - url: /sass
    static_dir: sass

  # Tangani semua file PHP
  - url: /(.+\.php)$
    script: \1

  # Default handler arahkan ke index.php (yang redirect ke login.php)
  - url: /.*
    script: index.php
