runtime: php81

handlers:
  - url: /css
    static_dir: css

  - url: /fonts
    static_dir: fonts

  - url: /img
    static_dir: img

  - url: /js
    static_dir: js

  - url: /sass
    static_dir: sass

  # Tangani semua file PHP secara langsung
  - url: /(.+\.php)$
    script: \1

  # Tangani root path saja ("/"), arahkan ke index.php
  - url: ^/$
    script: index.php

  # Tangani semua sisanya (misalnya HTML statis, dll)
  - url: /.*
    script: index.php
