runtime: php81

handlers:
  - url: /css
    static_dir: css

  - url: /fonts
    static_dir: fonts

  - url: /img
    static_dir: img

  - url: /js
    static_dir: js

  - url: /sass
    static_dir: sass

  # Tangani semua file .php langsung
  - url: /(.+\.php)$
    script: \1

  # Tangani root atau URL lainnya, arahkan ke login.php
  - url: /.*
    script: login.php
