runtime: php81

handlers:
  # 1. Tangani file statis (CSS/JS/Gambar)
  - url: /(.*\.(css|js|png|jpg|ico|gif|svg|woff2|woff|ttf|eot))
    static_files: \1
    upload: .*\.(css|js|png|jpg|ico|gif|svg|woff2|woff|ttf|eot)$

  # 2. Tangani file PHP secara eksplisit
  - url: /(.*\.php)
    script: \1

  # 3. Tangani root URL (/) ke login.php
  - url: /
    script: login.php

  # 4. Tangani semua URL lainnya (untuk routing aplikasi)
  - url: /.*
    script: login.php  # atau index.php jika Anda punya front controller
