runtime: php81

#entrypoint: serve login.php

handlers:
  - url: /css
    static_dir: css

  - url: /fonts
    static_dir: fonts

  - url: /img
    static_dir: img
    
  - url: /js
    static_dir: js

  - url: /sass
    static_dir: sass  
    
  - url: /login\.php
    script: login.php
    secure: always

  - url: /register\.php
    script: register.php
    secure: always
   
# Tangani semua file PHP yang valid
  - url: /(.*\.php)
    script: \1

  # Default handler jika file tidak cocok, arahkan ke login.php atau file utama
  - url: /.*
    script: login.php
