runtime: php81

entrypoint: serve index.php

handlers:
  - url: /(.+\.(css|js|png|jpg|gif|ico|woff|woff2|ttf|svg|eot))
    static_files: \1
    upload: .+\.(css|js|png|jpg|gif|ico|woff|woff2|ttf|svg|eot)

  - url: /.*
    script: auto
